name: bitrix_test
networks:
  bitrix_test_network:
    name: bitrix_test_network

services:
  web:
    build: ./web
    volumes:
      - ./html:/var/www/html/
    ports:
      - 127.0.0.151:80:80
    working_dir: /var/www/html/
    networks:
      - bitrix_test_network
    depends_on:
      - db
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - 3316:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bitrix_test_network
  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.151:81:80
    networks:
      - bitrix_test_network
    depends_on:
      - db
volumes:
  mysql-data:
