name: myapp

networks:
  my_network:
    name: my_network

services:
  nginx:
    container_name: nginx
    image: "nginx:stable-alpine"
    ports:
      - 8000:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/public_html
    networks:
      - my_network
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
    networks:
      - my_network
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=docker-test"
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./www:/var/www/public_html
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
    networks:
      - my_network
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
    networks:
      - my_network
    depends_on:
      - mysql

volumes:
  mysql-data: