name: git_test

networks:
  my_git_test:
    name: my_git_test

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/public_html
    depends_on:
      - php
      - mysql
    ports:
      - 8000:80
    networks:
      - my_git_test
  php:
    build: ./images/php
    container_name: php
    volumes:
      - ./www:/var/www/public_html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=docker-test"
    networks:
      - my_git_test
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./www:/var/www/public_html
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
    restart: always
    networks:
      - my_git_test
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    restart: always
    networks:
      - my_git_test
  redis:
    image: redis:alpine
    container_name: 'redis'
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --requirepass 12345 --include /usr/local/etc/redis/redis.conf
    networks:
      - my_git_test
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitUser
      - RABBITMQ_DEFAULT_PASS=rabbitPass
    networks:
      - my_git_test

volumes:
  mysql-data: